FROM quay.io/Mathiya578/sohan
RUN git clone https://github.com/Mathiya578/https://github.com/Mathiya578/Sohan-Matheesha /root/Mathiya578
WORKDIR /root/Mathiya578/
RUN yarn install --network-concurrency 1
CMD ["node", "lib/client.js"]
 
